lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # anciennement private_key_path
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # anciennement public_key_path
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
