<?php

namespace Container9gQ2CG0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S_OooIjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S.OooIj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S.OooIj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'registrationService' => ['privates', 'App\\Service\\InscriptionService', 'getInscriptionServiceService', true],
        ], [
            'registrationService' => 'App\\Service\\InscriptionService',
        ]);
    }
}
