<?php

namespace Container9gQ2CG0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllergetCategoriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MTCWnA5.App\Controller\AdminController::getCategories()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MTCWnA5.App\\Controller\\AdminController::getCategories()'] = ($container->privates['.service_locator.MTCWnA5'] ?? $container->load('get_ServiceLocator_MTCWnA5Service'))->withContext('App\\Controller\\AdminController::getCategories()', $container);
    }
}
