<?php

namespace Container9gQ2CG0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassementControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ClassementController' shared autowired service.
     *
     * @return \App\Controller\ClassementController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ClassementController.php';

        $container->services['App\\Controller\\ClassementController'] = $instance = new \App\Controller\ClassementController(($container->privates['App\\Repository\\SaleRepository'] ?? $container->load('getSaleRepositoryService')), ($container->privates['App\\Repository\\UsersRepository'] ?? $container->load('getUsersRepositoryService')), ($container->privates['App\\Repository\\GoalsRepository'] ?? $container->load('getGoalsRepositoryService')), ($container->privates['App\\Repository\\ItemsStockRepository'] ?? $container->load('getItemsStockRepositoryService')), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\ClassementController', $container));

        return $instance;
    }
}
