<?php

namespace Container9gQ2CG0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jfxTx3Z.App\Controller\ClientController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jfxTx3Z.App\\Controller\\ClientController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
            'saleRepository' => ['privates', 'App\\Repository\\SaleRepository', 'getSaleRepositoryService', true],
            'liveRepository' => ['privates', 'App\\Repository\\LiveRepository', 'getLiveRepositoryService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'usersRepository' => 'App\\Repository\\UsersRepository',
            'saleRepository' => 'App\\Repository\\SaleRepository',
            'liveRepository' => 'App\\Repository\\LiveRepository',
        ]))->withContext('App\\Controller\\ClientController::index()', $container);
    }
}
