<?php

namespace Container9gQ2CG0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoriqueControllerdetailsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CtyNz_i.App\Controller\HistoriqueController::details()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CtyNz_i.App\\Controller\\HistoriqueController::details()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'historyRepo' => ['privates', 'App\\Repository\\HistoryRepository', 'getHistoryRepositoryService', true],
        ], [
            'historyRepo' => 'App\\Repository\\HistoryRepository',
        ]))->withContext('App\\Controller\\HistoriqueController::details()', $container);
    }
}
