<?php

namespace Container9gQ2CG0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Item' shared autowired service.
     *
     * @return \App\Entity\Item
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Item.php';

        return $container->privates['App\\Entity\\Item'] = new \App\Entity\Item();
    }
}
