<?php

namespace Container9gQ2CG0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItemApiControllerreadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oTFA6TM.App\Controller\API\ItemApiController::read()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oTFA6TM.App\\Controller\\API\\ItemApiController::read()'] = ($container->privates['.service_locator.oTFA6TM'] ?? $container->load('get_ServiceLocator_OTFA6TMService'))->withContext('App\\Controller\\API\\ItemApiController::read()', $container);
    }
}
