<?php

namespace Container9gQ2CG0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockControllerApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\API\StockControllerApi' shared autowired service.
     *
     * @return \App\Controller\API\StockControllerApi
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/API/StockControllerApi.php';

        $container->services['App\\Controller\\API\\StockControllerApi'] = $instance = new \App\Controller\API\StockControllerApi(($container->privates['App\\Repository\\ItemsStockRepository'] ?? $container->load('getItemsStockRepositoryService')), ($container->privates['App\\Repository\\ExportTempRepository'] ?? $container->load('getExportTempRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\API\\StockControllerApi', $container));

        return $instance;
    }
}
