<?php

namespace ContainerXTavYxY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3UY9G_DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3UY9G.D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3UY9G.D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exportRepo' => ['privates', 'App\\Repository\\ExportTempRepository', 'getExportTempRepositoryService', true],
        ], [
            'exportRepo' => 'App\\Repository\\ExportTempRepository',
        ]);
    }
}
