<?php

namespace ContainerXTavYxY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerliveInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BgeHlYp.App\Controller\AdminController::liveInterface()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BgeHlYp.App\\Controller\\AdminController::liveInterface()'] = ($container->privates['.service_locator.BgeHlYp'] ?? $container->load('get_ServiceLocator_BgeHlYpService'))->withContext('App\\Controller\\AdminController::liveInterface()', $container);
    }
}
