<?php

namespace ContainerXTavYxY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerstartLiveSelectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jYyljJZ.App\Controller\AdminController::startLiveSelect()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jYyljJZ.App\\Controller\\AdminController::startLiveSelect()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'itemRepository' => ['privates', 'App\\Repository\\ItemRepository', 'getItemRepositoryService', true],
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'itemRepository' => 'App\\Repository\\ItemRepository',
            'usersRepository' => 'App\\Repository\\UsersRepository',
        ]))->withContext('App\\Controller\\AdminController::startLiveSelect()', $container);
    }
}
