<?php

namespace ContainerXTavYxY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerapiDashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZZG8GLe.App\Controller\AdminController::apiDashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZZG8GLe.App\\Controller\\AdminController::apiDashboard()'] = ($container->privates['.service_locator.ZZG8GLe'] ?? $container->load('get_ServiceLocator_ZZG8GLeService'))->withContext('App\\Controller\\AdminController::apiDashboard()', $container);
    }
}
