<?php

namespace ContainerXTavYxY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientControllerliveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hc.uNtg.App\Controller\ClientController::live()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hc.uNtg.App\\Controller\\ClientController::live()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
            'liveRepository' => ['privates', 'App\\Repository\\LiveRepository', 'getLiveRepositoryService', true],
        ], [
            'usersRepository' => 'App\\Repository\\UsersRepository',
            'liveRepository' => 'App\\Repository\\LiveRepository',
        ]))->withContext('App\\Controller\\ClientController::live()', $container);
    }
}
