<?php

namespace ContainerXTavYxY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoriqueControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E52XFpd.App\Controller\HistoriqueController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E52XFpd.App\\Controller\\HistoriqueController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'historyRepo' => ['privates', 'App\\Repository\\HistoryRepository', 'getHistoryRepositoryService', true],
            'stateRepo' => ['privates', 'App\\Repository\\StateCommandeRepository', 'getStateCommandeRepositoryService', true],
        ], [
            'historyRepo' => 'App\\Repository\\HistoryRepository',
            'stateRepo' => 'App\\Repository\\StateCommandeRepository',
        ]))->withContext('App\\Controller\\HistoriqueController::index()', $container);
    }
}
