<?php

namespace ContainerXTavYxY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiveApiControllerapiConfirmLiveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JNP1gW5.App\Controller\LiveApiController::apiConfirmLive()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JNP1gW5.App\\Controller\\LiveApiController::apiConfirmLive()'] = ($container->privates['.service_locator.JNP1gW5'] ?? $container->load('get_ServiceLocator_JNP1gW5Service'))->withContext('App\\Controller\\LiveApiController::apiConfirmLive()', $container);
    }
}
