<?php

namespace ContainerXTavYxY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiveApiControllerapiStartLiveSelectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fld4FZ4.App\Controller\LiveApiController::apiStartLiveSelect()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fld4FZ4.App\\Controller\\LiveApiController::apiStartLiveSelect()'] = ($container->privates['.service_locator.fld4FZ4'] ?? $container->load('get_ServiceLocator_Fld4FZ4Service'))->withContext('App\\Controller\\LiveApiController::apiStartLiveSelect()', $container);
    }
}
