<?php

namespace ContainerXTavYxY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilControllerprofilService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w3dsmyD.App\Controller\ProfilController::profil()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w3dsmyD.App\\Controller\\ProfilController::profil()'] = ($container->privates['.service_locator.w3dsmyD'] ?? $container->load('get_ServiceLocator_W3dsmyDService'))->withContext('App\\Controller\\ProfilController::profil()', $container);
    }
}
