<?php

namespace ContainerXTavYxY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PromotionController' shared autowired service.
     *
     * @return \App\Controller\PromotionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PromotionController.php';

        $container->services['App\\Controller\\PromotionController'] = $instance = new \App\Controller\PromotionController(($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')), ($container->privates['App\\Repository\\ItemRepository'] ?? $container->load('getItemRepositoryService')), ($container->privates['App\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService')), ($container->privates['App\\Repository\\UsersRepository'] ?? $container->load('getUsersRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\PromotionController', $container));

        return $instance;
    }
}
