<?php

namespace ContainerXTavYxY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockControllerApisaveExportRequestsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3UY9G.D.App\Controller\API\StockControllerApi::saveExportRequests()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3UY9G.D.App\\Controller\\API\\StockControllerApi::saveExportRequests()'] = ($container->privates['.service_locator.3UY9G.D'] ?? $container->load('get_ServiceLocator_3UY9G_DService'))->withContext('App\\Controller\\API\\StockControllerApi::saveExportRequests()', $container);
    }
}
