<?php

namespace ContainerXTavYxY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\StockController' shared autowired service.
     *
     * @return \App\Controller\StockController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/StockController.php';

        $container->services['App\\Controller\\StockController'] = $instance = new \App\Controller\StockController(($container->privates['App\\Repository\\ItemsStockRepository'] ?? $container->load('getItemsStockRepositoryService')), ($container->privates['App\\Repository\\ExportTempRepository'] ?? $container->load('getExportTempRepositoryService')), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\StockController', $container));

        return $instance;
    }
}
