<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXTavYxY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXTavYxY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXTavYxY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXTavYxY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXTavYxY\App_KernelDevDebugContainer([
    'container.build_hash' => 'XTavYxY',
    'container.build_id' => '7a1106b4',
    'container.build_time' => 1760649562,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXTavYxY');
